### ISSUE TITLE
compile and run for x86 devices

### ISSUE THREAD

**Issue by estiqaatsi** [ayuso2013/face-recognition#3]
Hi,

I'm a newbie in Eclipse ADT (Eclipse Luna, with OpenCV 2.4.10).
I successfully compiled your project getting the .apk, but once launched it on my actual hardware device (Samsung Galaxy Tab 3, w/Intel x86 processor) the app crashes with the message "Program OCV Face Recognition has been stopped" on the device.
If I download the app from the Play Store it works correctly, so I think it could be a target problem. Am I right?
May you please suggest how to fix this?
Should it be useful, below you will find the console log and the LogCat.

Thank you in advance.

====Console Log=====
[2015-03-11 18:28:12 - face-recognition] ------------------------------
[2015-03-11 18:28:12 - face-recognition] Android Launch!
[2015-03-11 18:28:12 - face-recognition] adb is running normally.
[2015-03-11 18:28:12 - face-recognition] Performing org.opencv.javacv.facerecognition.FdActivity activity launch
[2015-03-11 18:28:12 - face-recognition] Automatic Target Mode: using device '3200e20e6ec69000'
[2015-03-11 18:28:12 - face-recognition] Uploading face-recognition.apk onto device '3200e20e6ec69000'
[2015-03-11 18:28:16 - face-recognition] Installing face-recognition.apk...
[2015-03-11 18:28:25 - face-recognition] Success!
[2015-03-11 18:28:25 - face-recognition] Project dependency found, installing: OpenCV Library - 2.4.10
[2015-03-11 18:28:25 - OpenCV Library - 2.4.10] Uploading OpenCV Library - 2.4.10.apk onto device '3200e20e6ec69000'
[2015-03-11 18:28:25 - OpenCV Library - 2.4.10] Installing OpenCV Library - 2.4.10.apk...
[2015-03-11 18:28:34 - OpenCV Library - 2.4.10] Success!
[2015-03-11 18:28:34 - face-recognition] Starting activity org.opencv.javacv.facerecognition.FdActivity on device 3200e20e6ec69000
[2015-03-11 18:28:36 - face-recognition] ActivityManager: Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=org.opencv.javacv.facerecognition/.FdActivity }
====END Console Log=====

===== LogCat============
03-11 18:28:36.233: E/SELinux(19796): [DEBUG] seapp_context_lookup: seinfoCategory = default
03-11 18:28:36.233: D/dalvikvm(19796): Late-enabling CheckJNI
03-11 18:28:36.233: D/dalvikvm(19796): Try to disable coredump for pid 19796
03-11 18:28:36.233: D/dalvikvm(19796): Process 19796 nice name: org.opencv.javacv.facerecognition
03-11 18:28:36.233: D/dalvikvm(19796): Extra Options: not specified
03-11 18:28:36.273: I/dalvikvm(19796): Enabling JNI app bug workarounds for target SDK version 8...
03-11 18:28:36.443: D/dalvikvm(19796): GC_FOR_ALLOC freed 910K, 25% free 4946K/6520K, paused 3ms, total 3ms
03-11 18:28:36.453: D/dalvikvm(19796): GC_FOR_ALLOC freed 816K, 25% free 4984K/6632K, paused 2ms, total 2ms
03-11 18:28:36.463: D/dalvikvm(19796): GC_FOR_ALLOC freed 885K, 26% free 4977K/6672K, paused 11ms, total 11ms
03-11 18:28:36.493: I/dalvikvm(19796): Failed resolving Lorg/opencv/javacv/facerecognition/FdActivity; interface 1201 'Lorg/opencv/android/CameraBridgeViewBase$CvCameraViewListener2;'
03-11 18:28:36.493: W/dalvikvm(19796): Link of class 'Lorg/opencv/javacv/facerecognition/FdActivity;' failed
03-11 18:28:36.493: D/AndroidRuntime(19796): Shutting down VM
03-11 18:28:36.493: W/dalvikvm(19796): threadid=1: thread exiting with uncaught exception (group=0x4331d1a0)
03-11 18:28:36.493: E/AndroidRuntime(19796): FATAL EXCEPTION: main
03-11 18:28:36.493: E/AndroidRuntime(19796): Process: org.opencv.javacv.facerecognition, PID: 19796
03-11 18:28:36.493: E/AndroidRuntime(19796): java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{org.opencv.javacv.facerecognition/org.opencv.javacv.facerecognition.FdActivity}: java.lang.ClassNotFoundException: Didn't find class "org.opencv.javacv.facerecognition.FdActivity" on path: DexPathList[[zip file "/data/app/org.opencv.javacv.facerecognition-9.apk"],nativeLibraryDirectories=[/data/app-lib/org.opencv.javacv.facerecognition-9, /vendor/lib, /system/lib, /system/lib/arm]]
03-11 18:28:36.493: E/AndroidRuntime(19796): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2307)
03-11 18:28:36.493: E/AndroidRuntime(19796): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2464)
03-11 18:28:36.493: E/AndroidRuntime(19796): 	at android.app.ActivityThread.access$900(ActivityThread.java:172)
03-11 18:28:36.493: E/AndroidRuntime(19796): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
03-11 18:28:36.493: E/AndroidRuntime(19796): 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-11 18:28:36.493: E/AndroidRuntime(19796): 	at android.os.Looper.loop(Looper.java:146)
03-11 18:28:36.493: E/AndroidRuntime(19796): 	at android.app.ActivityThread.main(ActivityThread.java:5653)
03-11 18:28:36.493: E/AndroidRuntime(19796): 	at java.lang.reflect.Method.invokeNative(Native Method)
03-11 18:28:36.493: E/AndroidRuntime(19796): 	at java.lang.reflect.Method.invoke(Method.java:515)
03-11 18:28:36.493: E/AndroidRuntime(19796): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
03-11 18:28:36.493: E/AndroidRuntime(19796): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
03-11 18:28:36.493: E/AndroidRuntime(19796): 	at dalvik.system.NativeStart.main(Native Method)
03-11 18:28:36.493: E/AndroidRuntime(19796): Caused by: java.lang.ClassNotFoundException: Didn't find class "org.opencv.javacv.facerecognition.FdActivity" on path: DexPathList[[zip file "/data/app/org.opencv.javacv.facerecognition-9.apk"],nativeLibraryDirectories=[/data/app-lib/org.opencv.javacv.facerecognition-9, /vendor/lib, /system/lib, /system/lib/arm]]
03-11 18:28:36.493: E/AndroidRuntime(19796): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
03-11 18:28:36.493: E/AndroidRuntime(19796): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
03-11 18:28:36.493: E/AndroidRuntime(19796): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
03-11 18:28:36.493: E/AndroidRuntime(19796): 	at android.app.Instrumentation.newActivity(Instrumentation.java:1067)
03-11 18:28:36.493: E/AndroidRuntime(19796): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
03-11 18:28:36.493: E/AndroidRuntime(19796): 	... 11 more
===== END LogCat============

**Comment by estiqaatsi** [comment]
I imported the whole project, along with its dependencies, in Android Studio, and it worked!
No modifications, just the import tool of Android Studio.
That's it.

Thank you anyway.

**Comment by ayuso2013** [comment]
Great!

2015-03-11 20:59 GMT+01:00 estiqaatsi <notifications@github.com>:
