### ISSUE TITLE
Running the project with Android Studio

### ISSUE THREAD

**Issue by sarangborude** [ayuso2013/face-recognition#8]
Hi, 

I imported the project in Android studio. Got rid of all the errors. Now the app compiles and crashes on runtime. Can you please tell me how to get it to work?

What version of android SDK for OpenCV are you using? I think it is OpenCV 2.4.6, but I cannot seem to find the download for it, so I used OpenCV 2.4.9

I am using Gradle 2.10 to compile and Android studio 2.0 Preview 6. 

Here the logcat when I run the app

01-22 01:37:30.450 13827-13836/org.opencv.javacv.facerecognition I/art: Thread[5,tid=13836,WaitingInMainSignalCatcherLoop,Thread*=0xf3c3dd00,peer=0x1da030a0,"Signal Catcher"]: reacting to signal 3
01-22 01:37:30.545 13827-13836/org.opencv.javacv.facerecognition I/art: Wrote stack traces to '/data/anr/traces.txt'
01-22 01:38:00.540 13827-14776/org.opencv.javacv.facerecognition D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
01-22 01:38:03.770 13827-13888/org.opencv.javacv.facerecognition I/art: Explicit concurrent mark sweep GC freed 510(54KB) AllocSpace objects, 2(32KB) LOS objects, 24% free, 17MB/23MB, paused 139us total 11.365ms
01-22 01:38:03.792 13827-13888/org.opencv.javacv.facerecognition I/art: Explicit concurrent mark sweep GC freed 41(1392B) AllocSpace objects, 0(0B) LOS objects, 24% free, 17MB/23MB, paused 162us total 10.487ms
01-22 01:38:03.813 13827-13888/org.opencv.javacv.facerecognition I/art: Explicit concurrent mark sweep GC freed 3(96B) AllocSpace objects, 0(0B) LOS objects, 24% free, 17MB/23MB, paused 136us total 9.790ms
01-22 01:38:03.835 13827-13888/org.opencv.javacv.facerecognition I/art: Explicit concurrent mark sweep GC freed 3(96B) AllocSpace objects, 0(0B) LOS objects, 24% free, 17MB/23MB, paused 135us total 9.761ms
01-22 01:38:03.856 13827-13888/org.opencv.javacv.facerecognition I/art: Explicit concurrent mark sweep GC freed 3(96B) AllocSpace objects, 0(0B) LOS objects, 24% free, 17MB/23MB, paused 136us total 9.759ms
01-22 01:38:09.447 13827-13827/org.opencv.javacv.facerecognition I/Process: Sending signal. PID: 13827 SIG: 9
01-22 01:38:17.717 15155-15155/org.opencv.javacv.facerecognition I/fd: BootstrapApplication created. Android package is org.opencv.javacv.facerecognition, real application class is null.
01-22 01:38:17.718 15155-15155/org.opencv.javacv.facerecognition V/fd: Cannot find external resources, not patching them in
01-22 01:38:17.719 15155-15155/org.opencv.javacv.facerecognition I/fd: Resource override is null
01-22 01:38:17.719 15155-15155/org.opencv.javacv.facerecognition V/fd: Cannot find newer dex classes, not patching them in
01-22 01:38:17.719 15155-15155/org.opencv.javacv.facerecognition I/fd: No override .dex files found
01-22 01:38:17.722 15155-15155/org.opencv.javacv.facerecognition I/fd: Starting server socket listening for package org.opencv.javacv.facerecognition on android.net.LocalSocketAddress@1e82075b
01-22 01:38:17.723 15155-15155/org.opencv.javacv.facerecognition I/fd: Started server for package org.opencv.javacv.facerecognition
01-22 01:38:17.767 15155-15155/org.opencv.javacv.facerecognition I/OCVSample::Activity: Instantiated new class org.opencv.javacv.facerecognition.FdActivity
01-22 01:38:17.780 15155-15155/org.opencv.javacv.facerecognition I/OCVSample::Activity: called onCreate
01-22 01:38:17.861 15155-15155/org.opencv.javacv.facerecognition D/CameraBridge: Attr count: 4
01-22 01:38:17.894 15155-15155/org.opencv.javacv.facerecognition E/Error: Error creating directory
01-22 01:38:17.896 15155-15155/org.opencv.javacv.facerecognition D/AndroidRuntime: Shutting down VM
01-22 01:38:17.897 15155-15155/org.opencv.javacv.facerecognition E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                   Process: org.opencv.javacv.facerecognition, PID: 15155
                                                                                   java.lang.RuntimeException: Unable to resume activity {org.opencv.javacv.facerecognition/org.opencv.javacv.facerecognition.FdActivity}: java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=org.opencv.engine.BIND }
                                                                                       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2986)
                                                                                       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3017)
                                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392)
                                                                                       at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                       at android.os.Looper.loop(Looper.java:135)
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5258)
                                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
                                                                                    Caused by: java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=org.opencv.engine.BIND }
                                                                                       at android.app.ContextImpl.validateServiceIntent(ContextImpl.java:1680)
                                                                                       at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1779)
                                                                                       at android.app.ContextImpl.bindService(ContextImpl.java:1757)
                                                                                       at android.content.ContextWrapper.bindService(ContextWrapper.java:539)
                                                                                       at org.opencv.android.AsyncServiceHelper.initOpenCV(AsyncServiceHelper.java:24)
                                                                                       at org.opencv.android.OpenCVLoader.initAsync(OpenCVLoader.java:79)
                                                                                       at org.opencv.javacv.facerecognition.FdActivity.onResume(FdActivity.java:429)
                                                                                       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1257)
                                                                                       at android.app.Activity.performResume(Activity.java:6076)
                                                                                       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2975)
                                                                                       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3017) 
                                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392) 
                                                                                       at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                       at android.os.Looper.loop(Looper.java:135) 
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5258) 
                                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901) 
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)

**Comment by ayuso2013** [comment]
The project imported into Android Studio

https://docs.google.com/file/d/0B5yf1GPHtiNId1ZWU252elFrSzg/edit?usp=drive_web

Redards.

2016-01-22 2:52 GMT+01:00 sarangborude <notifications@github.com>:

**Comment by sarangborude** [comment]
Thanks,
It works. The mistake I was doing is using API 22 and 23. And for some reason it was crashing. 
Any way that we can used OpenCV3 instead of 2.4.10??

**Comment by saffull** [comment]
I think in the loadcall back function you should say which version you are using...
